# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddsseventh.xdc

# Block Designs: bd/ddsseventh/ddsseventh.bd
# Block Designs: The module: 'ddsseventh' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ddsseventh/ip/ddsseventh_dds_compiler_0_0/ddsseventh_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_dds_compiler_0_0 || ORIG_REF_NAME==ddsseventh_dds_compiler_0_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_clk_wiz_0_0/ddsseventh_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_clk_wiz_0_0 || ORIG_REF_NAME==ddsseventh_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_ila_0_0/ddsseventh_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_ila_0_0 || ORIG_REF_NAME==ddsseventh_ila_0_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_dds_compiler_1_0/ddsseventh_dds_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_dds_compiler_1_0 || ORIG_REF_NAME==ddsseventh_dds_compiler_1_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_mult_gen_0_3/ddsseventh_mult_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_mult_gen_0_3 || ORIG_REF_NAME==ddsseventh_mult_gen_0_3} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/ddsseventh_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_fir_compiler_0_0 || ORIG_REF_NAME==ddsseventh_fir_compiler_0_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_xlconstant_0_0/ddsseventh_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_xlconstant_0_0 || ORIG_REF_NAME==ddsseventh_xlconstant_0_0} -quiet] -quiet

# IP: bd/ddsseventh/ip/ddsseventh_mult_gen_1_0/ddsseventh_mult_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddsseventh_mult_gen_1_0 || ORIG_REF_NAME==ddsseventh_mult_gen_1_0} -quiet] -quiet

# XDC: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.gen/sources_1/bd/ddsseventh/ddsseventh_ooc.xdc
