set_property SRC_FILE_INFO {cfile:/home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.srcs/constrs_1/new/ddsseventh.xdc rfile:../../../ddsseventh.srcs/constrs_1/new/ddsseventh.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {clock}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE BUF [get_ports {clock}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {reset}]
