#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 04 11:50:05 IST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ddsseventh_time_synth -key {Post-Synthesis:sim_1:Timing:ddsseventh} -tclbatch ddsseventh.tcl -protoinst "protoinst_files/ddsseventh.protoinst" -log simulate.log"
xsim ddsseventh_time_synth -key {Post-Synthesis:sim_1:Timing:ddsseventh} -tclbatch ddsseventh.tcl -protoinst "protoinst_files/ddsseventh.protoinst" -log simulate.log

