# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.srcs/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/ddsseventh_fir_compiler_0_0.xci
# IP: The module: 'ddsseventh_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.gen/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddsseventh_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.gen/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/ddsseventh_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddsseventh_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.srcs/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/ddsseventh_fir_compiler_0_0.xci
# IP: The module: 'ddsseventh_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.gen/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddsseventh_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/arun/FPGA_Ultra_new/Keep_Safe_FPGA/ddsseventh/ddsseventh.gen/sources_1/bd/ddsseventh/ip/ddsseventh_fir_compiler_0_0/ddsseventh_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddsseventh_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
